name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # 개인 토큰을 사용할 것인지 말 것인지
        persist-credentials: false
    - name: pip upgrade
      run: python -m pip install --upgrade pip
    - name: pip install
      run: pip install -r requirements.txt
    - name: python execute
      run: python test.py
    - name: commit changes
      run: |
        git config --local user.email "admin"
        git config --local user.name "admin"
        git add .
        git commit -m "test"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
